# Generated by Django 4.2.6 on 2024-02-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
